import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import '../../app/theme.dart';
import '../../models/catalog_product_model.dart';
import '../../models/order_model.dart'; // For AddressModel and OrderModel
import '../../services/auth_service.dart';
import '../../services/firestore_service.dart';
import '../common/premium_widgets.dart';

class CheckoutSheet extends StatefulWidget {
  final CatalogProductModel product;
  final ProductVariation? selectedVariation;
  final double price;

  const CheckoutSheet({
    super.key,
    required this.product,
    this.selectedVariation,
    required this.price,
  });

  @override
  State<CheckoutSheet> createState() => _CheckoutSheetState();
}

class _CheckoutSheetState extends State<CheckoutSheet> {
  final _formKey = GlobalKey<FormState>();
  
  // Form Controllers
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _streetController = TextEditingController();
  final _cityController = TextEditingController();
  final _pincodeController = TextEditingController();
  // State is hardcoded to 'Tamil Nadu' or simple field for now
  final _stateController = TextEditingController(text: 'Tamil Nadu');

  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _prefillUserData();
  }

  void _prefillUserData() {
    final user = context.read<AuthService>().currentUserModel;
    if (user != null) {
      _nameController.text = user.displayName;
      _phoneController.text = user.phoneNumber;
      // If we had saved addresses, we'd prefill here
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    _streetController.dispose();
    _cityController.dispose();
    _pincodeController.dispose();
    _stateController.dispose();
    super.dispose();
  }

  Future<void> _placeOrder() async {
    if (!_formKey.currentState!.validate()) return;
    
    setState(() => _isLoading = true);

    try {
      final firestoreService = context.read<FirestoreService>();
      final authService = context.read<AuthService>();
      final userId = authService.currentUser?.uid;

      if (userId == null) {
        throw Exception('User not logged in');
      }

      final address = AddressModel(
        name: _nameController.text.trim(),
        phone: _phoneController.text.trim(),
        street: _streetController.text.trim(),
        city: _cityController.text.trim(),
        state: _stateController.text.trim(),
        pincode: _pincodeController.text.trim(),
      );

      // Create Order Item
      final orderItem = OrderItem(
        productId: widget.product.id,
        variationId: widget.selectedVariation?.id,
        productName: widget.product.name,
        productImage: widget.product.images.isNotEmpty ? widget.product.images.first : '',
        selectedAttributes: widget.selectedVariation?.attributes ?? {},
        quantity: 1, // Simple quantity for now
        price: widget.price,
        warrantyMonths: widget.selectedVariation?.warrantyMonths ?? widget.product.warrantyMonths,
      );

      final order = OrderModel(
        id: '', // Generated by firestoreService
        userId: userId,
        items: [orderItem],
        totalAmount: widget.price, // + Delivery Fee if any
        address: address,
        orderedAt: DateTime.now(),
        paymentMethod: 'COD',
      );

      final orderId = await firestoreService.placeOrder(order);

      if (mounted) {
        Navigator.pop(context); // Close sheet
        _showSuccessDialog(context, orderId);
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error placing order: $e')),
      );
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _showSuccessDialog(BuildContext context, String orderId) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppTheme.success.withAlpha(20),
                shape: BoxShape.circle,
              ),
              child: const Icon(Icons.check_circle, color: AppTheme.success, size: 48),
            ),
            const SizedBox(height: 16),
            Text('Order Placed!', style: Theme.of(context).textTheme.headlineSmall),
            const SizedBox(height: 8),
            Text('Order ID: ${orderId.substring(orderId.length - 6).toUpperCase()}'),
            const SizedBox(height: 16),
            const Text(
              'Your order has been placed successfully.\nYou can track it in the Requests tab.',
              textAlign: TextAlign.center,
              style: TextStyle(color: AppTheme.textSecondaryLight),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () {
               context.pop(); // Close dialog
               context.go('/home'); // Go home
            },
            child: const Text('Back to Home'),
          ),
          ElevatedButton(
            onPressed: () {
              context.pop();
              // context.push('/orders'); // TODO: Create user orders screen if separate from requests
              // For now simpler to go home
              context.go('/home'); 
            },
            child: const Text('View Orders'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      padding: EdgeInsets.fromLTRB(20, 20, 20, MediaQuery.of(context).viewInsets.bottom + 20),
      constraints: BoxConstraints(maxHeight: MediaQuery.of(context).size.height * 0.85),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Handle
          Center(
            child: Container(
              width: 40, height: 4,
              decoration: BoxDecoration(color: AppTheme.borderLight, borderRadius: BorderRadius.circular(2)),
            ),
          ),
          const SizedBox(height: 20),
          Text('Checkout', style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold)),
          const SizedBox(height: 20),
          
          Flexible(
            child: SingleChildScrollView(
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Order Summary
                    Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: AppTheme.backgroundLight,
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: Row(
                        children: [
                          if (widget.product.images.isNotEmpty)
                             ClipRRect(borderRadius: BorderRadius.circular(8), child: Image.network(widget.product.images.first, width: 60, height: 60, fit: BoxFit.cover)),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(widget.product.name, style: const TextStyle(fontWeight: FontWeight.bold), maxLines: 1),
                                if (widget.selectedVariation != null)
                                  Text(
                                    widget.selectedVariation!.attributes.values.join(', '),
                                    style: const TextStyle(fontSize: 12, color: AppTheme.textSecondaryLight),
                                  ),
                                Text('₹${widget.price.toStringAsFixed(0)}', style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.primary)),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),
                    
                    // Shipping Address Form
                    Text('Shipping Address', style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold)),
                    const SizedBox(height: 12),
                    TextFormField(
                      controller: _nameController,
                      decoration: const InputDecoration(labelText: 'Full Name', prefixIcon: Icon(Icons.person_outline)),
                      validator: (v) => v!.isEmpty ? 'Required' : null,
                    ),
                    const SizedBox(height: 12),
                    TextFormField(
                      controller: _phoneController,
                      keyboardType: TextInputType.phone,
                      decoration: const InputDecoration(labelText: 'Phone Number', prefixIcon: Icon(Icons.phone_outlined)),
                      validator: (v) => v!.length < 10 ? 'Invalid Phone' : null,
                    ),
                     const SizedBox(height: 12),
                    TextFormField(
                      controller: _streetController,
                      decoration: const InputDecoration(labelText: 'Street / Area', prefixIcon: Icon(Icons.home_outlined)),
                      validator: (v) => v!.isEmpty ? 'Required' : null,
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(child: TextFormField(
                           controller: _cityController,
                           decoration: const InputDecoration(labelText: 'City'),
                           validator: (v) => v!.isEmpty ? 'Required' : null,
                        )),
                        const SizedBox(width: 12),
                        Expanded(child: TextFormField(
                           controller: _pincodeController,
                           keyboardType: TextInputType.number,
                           decoration: const InputDecoration(labelText: 'Pincode'),
                           validator: (v) => v!.length != 6 ? 'Invalid PIN' : null,
                        )),
                      ],
                    ),
                    
                    const SizedBox(height: 24),
                    // Payment Method
                    Text('Payment Method', style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold)),
                    const SizedBox(height: 12),
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        border: Border.all(color: AppTheme.primary),
                        borderRadius: BorderRadius.circular(12),
                        color: AppTheme.primary.withAlpha(10),
                      ),
                      child: const Row(
                        children: [
                          Icon(Icons.money, color: AppTheme.primary),
                          SizedBox(width: 12),
                          Text('Cash on Delivery', style: TextStyle(fontWeight: FontWeight.bold, color: AppTheme.primary)),
                          Spacer(),
                          Icon(Icons.check_circle, color: AppTheme.primary),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),
                  ],
                ),
              ),
            ),
          ),
          
          ElevatedButton(
            onPressed: _isLoading ? null : _placeOrder,
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.primary,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 16),
            ),
            child: _isLoading 
                ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                : Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text('Confirm Order'),
                    const SizedBox(width: 8),
                    Text('• ₹${widget.price.toStringAsFixed(0)}', style: TextStyle(color: Colors.white.withAlpha(200))),
                  ],
                ),
          ),
        ],
      ),
    );
  }
}
