org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx2G
android.useAndroidX=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
kotlin.daemon.useFallbackStrategy=true
kotlin.incremental=true
