// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAXPM-FnxF9w21AODhUb2MXi_fzryg5U',
    appId: '1:683528535970:web:f544d83861eeb605b53cfb',
    messagingSenderId: '683528535970',
    projectId: 'freelancing-c82c1',
    authDomain: 'freelancing-c82c1.firebaseapp.com',
    storageBucket: 'freelancing-c82c1.firebasestorage.app',
    measurementId: 'G-NJTFF535EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCofRwCXYe32xcu2jzGk30_AtlfutiJZAM',
    appId: '1:683528535970:android:cf3ab0982ab0b885b53cfb',
    messagingSenderId: '683528535970',
    projectId: 'freelancing-c82c1',
    storageBucket: 'freelancing-c82c1.firebasestorage.app',
  );
}
